[project]
name = "albzBlog"
version = "1.0.1"
description = "The basic blog app built in the Flask tutorial by alBz."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"